[theme]
base = "light"
primaryColor = "#1B2CC1"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F1F5F9"
textColor = "#0F172A"
font = "sans serif"

[server]
maxUploadSize = 5

[browser]
gatherUsageStats = false
